[window]
screen_size = "1280x720"
app_position = "50,50"

[parser]
ignored_class_list = [
    "AgeConfigDef",
    "BoundBodyPartGroupDefs",
    "HediffTargetBodyPartDefs",
    "MainButtonDef",
    "PawnColumnDef",
    "PawnTableDef",
    "RaceGroupDef",
    "SoundDef",
    "StringListDef",
    "Tags",
    "allowedMeditationFocusTypes",
    "apparel",
    "appliedOnFixedBodyParts",
    "backstoryCategories",
    "bodyTypeFemale",
    "bodyTypeGlobal",
    "bodyTypeMale",
    "childrenDefs",
    "conflictingTraits",
    "diseasePartsToAffect",
    "fixedIngredientFilter",
    "ingredients",
    "modExtensions",
    "parentDefs",
    "pawnKindNames",
    "raceNames",
    "randomMentalStateMtbDaysMoodCurve",
    "recipeMaker",
    "recipeUsers",
    "rulesFiles",
    "severityCurve",
    "severityPerDayIncrease",
    "severityPerDayReduce",
    "skillGains",
    "skillNeedFactors",
    "soldThoughts",
    "spawnCategories",
    "stuffCategories",
    "tags",
    "thingCategories",
    "thinkRoot",
    "prerequisites",
    "requiredResearchFacilities",
]
ignored_tag_list = [
    "DefaultBodyPart",
    "FluidType",
    "RMBLabelF",
    "RMBLabelM",
    "SocialImpact",
    "ThingDef",
    "Vulnerability",
    "addictionHediff",
    "addsHediff",
    "altitudeLayer",
    "appliedOnFixedBodyParts",
    "bleedRate",
    "capacity",
    "category",
    "categoryName",
    "checkOverrideOnDamage",
    "chemical",
    "color",
    "comment",
    "compClass",
    "defName",
    "defaultFactionType",
    "defaultLabelColor",
    "diedThought",
    "diedThoughtFemale",
    "diseaseIncident",
    "driverClass",
    "drugCategory",
    "effectWorking",
    "equipped_hediff",
    "family",
    "fluidType",
    "focusTypes",
    "foodType",
    "frostbiteVulnerability",
    "glowColor",
    "graphicClass",
    "harvestTag",
    "harvestedThingDef",
    "hatcherPawn",
    "hediff",
    "hediffClass",
    "hediffDef",
    "hediffName",
    "hediffSkin",
    "hediffSolid",
    "hitPoints",
    "identifier",
    "ingestEffect",
    "ingestEffectEat",
    "ingestSound",
    "initialResistanceRang",
    "initialResistanceRange",
    "initialWillRang",
    "initialWillRange",
    "initiatorXpGainSkill",
    "insertTag",
    "itemQuality",
    "joyKind",
    "keyword",
    "killedThought",
    "killedThoughtFemale",
    "lostThought",
    "lostThoughtFemale",
    "minIntelligence",
    "modExtensions",
    "nameColor",
    "need",
    "needClass",
    "offset",
    "optimalityOffsetFeedingAnimals",
    "optimalityOffsetHumanlikes",
    "parent",
    "path",
    "preferability",
    "randomMentalState",
    "recipeMaker",
    "recipientThought",
    "removesHediff",
    "researchPrerequisite",
    "skinCovered",
    "slot",
    "soul_type",
    "soundWorking",
    "spawnThingOnRemoved",
    "statDef",
    "statDef",
    "stateClass",
    "stringA",
    "symbol",
    "targetClass",
    "tasteThought",
    "techLevel",
    "texPath",
    "thingClass",
    "thoughtClass",
    "tickerType",
    "toStringStyle",
    "toleranceChemical",
    "toleranceHediff",
    "tradeability",
    "type",
    "useJob",
    "useLabel",
    "visualSizeRange",
    "workDisables",
    "workSkill",
    "workSpeedStat",
    "workerClass",
    "def",
    "tab",
    "incident",
    "only",
    "colorGenerator",
    "max",
    "shieldTexPath",
    "min",
    "requiredResearchBuilding",
    "quality",
]
